### ISSUE TITLE
Can we have reportFormat "RDF" as well for sbomType "SPDX_22"

### ISSUE THREAD

**Issue by ManjulaSuryabhatla** [philips-software/blackduck-report-action#17]
sbomType "SPDX_22" allows reportFormat values of "JSON", "RDF", "TAGVALUE" or "YAML".

**Comment by JeroenKnoops** [comment]
Related to: https://github.com/philips-software/blackduck-report-action/issues/1

**Comment by JeroenKnoops** [comment]
Implemented in #18
